services:
  nginx:
    image: nginx-sc23
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
      - ./sc23.key:/etc/nginx/ssl/sc23.key
      - ./sc23.crt:/etc/nginx/ssl/sc23.crt
    depends_on:
      - renting
      - padel-api
      - padel-radar
      - wise-frog
      - status
      - ligapb
    networks:
      - the-main-network

  status:
    image: status
    build:
      context: projects/docker-stats-fastapi
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - the-main-network

  renting:
    image: astro-renting
    build:
      context: projects/renting-data-generator
      dockerfile: Dockerfile
    networks:
      - the-main-network

  wise-frog:
    image: wise-frog
    build:
      context: projects/wise-frog
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - the-main-network


  padel-radar:
    image: padel-radar
    build:
      context: projects/padel-radar-app
      dockerfile: Dockerfile
    depends_on:
      - padel-api
    networks:
      - the-main-network

  ligapb:
    image: ligapb
    build:
      context: projects/ligapb
      dockerfile: Dockerfile
    networks:
      - the-main-network

  padel-api:
    environment:
      - PT_ENV=${PT_ENV}
      - PT_ALLOWED_ORIGINS=${PT_ALLOWED_ORIGINS}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - LOCATION_IQ_API_KEY=${LOCATION_IQ_API_KEY}
      - CACHE_REDIS_HOST=padel-redis
    image: padel-api
    build:
      context: projects/padel-tavernes
      dockerfile: Dockerfile
    volumes:
      - ../padel-tavernes/app:/app/app
    depends_on:
      - padel-redis
      # - padel-postgres
    networks:
      - the-main-network

  padel-redis:
    image: redis:alpine
    networks:
      - the-main-network

networks:
  the-main-network:
    driver: bridge
